apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: drone-secrets
  namespace: drone-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: drone-kubernetes-secrets
      version: "0.1.4"
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: drone
      interval: 12h
  values:
    extraSecretNamesForEnvFrom:
      - drone-kubernetes
    rbac:
      secretNamespace: drone-runner
    env:
      KUBERNETES_NAMESPACE: drone-runner
      DEBUG: 1
