apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: drone
  namespace: drone
spec:
  interval: 30m
  chart:
    spec:
      chart: drone
      version: "0.6.5"
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: drone
      interval: 12h
  values:
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: horel-ca-issuer
        cert-manager.io/common-name: drone.horel.io
        traefik.ingress.kubernetes.io/router.middlewares: drone-http-to-https@kubernetescrd
      hosts:
        - host: drone.horel.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: drone-server-tls
          hosts:
            - drone.horel.io
    env:
      DRONE_SERVER_HOST: drone.horel.io
      DRONE_SERVER_PROTO: https
      DRONE_USER_FILTER: cmhorel
      DRONE_DEBUG: true
    extraSecretNamesForEnvFrom:
      - drone
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
