apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-runner-cache
  namespace: drone-runner
spec:
  storageClassName: "local-path" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: drone-runner-cache
