apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone
  namespace: drone
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: drone
  data:
    - secretKey: DRONE_GITHUB_CLIENT_ID
      remoteRef:
        key: kv/drone/app-secrets
        property: DRONE_GITHUB_CLIENT_ID
    - secretKey: DRONE_GITHUB_CLIENT_SECRET
      remoteRef:
        key: kv/drone/app-secrets
        property: DRONE_GITHUB_CLIENT_SECRET
    - secretKey: DRONE_RPC_SECRET
      remoteRef:
        key: kv/drone/app-secrets
        property: DRONE_RPC_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone-runner
  namespace: drone-runner
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: drone-runner
  data:
    - secretKey: DRONE_RPC_SECRET
      remoteRef:
        key: kv/drone/app-secrets
        property: DRONE_RPC_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone-runner-dockerhub
  namespace: drone-runner
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: drone-runner-dockerhub
  data:
    - secretKey: password
      remoteRef:
        key: kv/drone/dockerhub-creds
        property: token
    - secretKey: username
      remoteRef:
        key: kv/drone/dockerhub-creds
        property: username
