apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: drone-runner
  namespace: drone-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: drone-runner-docker
      version: "0.6.2"
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: drone
      interval: 12h
  values:
    env:
      DRONE_SERVER_HOST: https://drone.horel.io
      DRONE_RPC_HOST: drone.drone.svc.cluster.local:8080
    extraSecretNamesForEnvFrom:
      - drone-runner
