apiVersion: external-secrets.io/v1alpha1
kind: ClusterExternalSecret
metadata:
  name: regcred
spec:
  externalSecretName: regcred
  namespaceSelector:
    matchLabels:
      horel.io.regcred.create: "1"
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: regcred
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
      name: regcred
      creationPolicy: Owner
    data:
      - secretKey: dockerconfigjson
        remoteRef:
          key: kv/drone/dockerhub-creds
          property: dockerconfigjson
