apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "v0.9.16"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 12h
  values:
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 150m
          memory: 100Mi
    certController:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 150m
          memory: 200Mi
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 150m
        memory: 100Mi

# serviceMonitor:
#   enabled: true
#   additionalLabels:
#     release: kube-prometheus-stack
