apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets-namespace.yaml
  - external-secrets-helmrepository.yaml
  - external-secrets-helmrelease.yaml
  - cluster-secret-store.yaml
