apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  interval: 30m
  chart:
    spec:
      chart: filebrowser
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: filebrowser
        namespace: filebrowser
      interval: 12h
  values:
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 30Mi
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: horel-ca-issuer
        cert-manager.io/common-name: files.horel.io
        traefik.ingress.kubernetes.io/router.middlewares: filebrowser-http-to-https@kubernetescrd
      hosts:
        - host: files.horel.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: filebrowser-server-tls
          hosts:
            - files.horel.io
    nodeSelector:
      horel.io.filebrowser: "true"
    config:
      auth:
        method: noauth
