apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - filebrowser-namespace.yaml
  - filebrowser-helmrepository.yaml
  - filebrowser-helmrelease.yaml
  - filebrowser-middleware.yaml
