apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy
  namespace: trivy
spec:
  interval: 30m
  chart:
    spec:
      chart: trivy-operator
      version: "v0.22.1"
      sourceRef:
        kind: HelmRepository
        name: trivy
        namespace: trivy
      interval: 12h
  values:
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 800m
        memory: 400Mi
    service:
      name: trivy
      #type: LoadBalancer
      port: 4954
      clusterIP: ""
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
    nodeCollector:
      tolerations:
        - effect: "NoSchedule"
          key:  "node-role.kubernetes.io/master" 
          operator: "Exists"

