apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: pihole
  namespace: pihole
spec:
  template:
    spec:
      containers:
        - name: pihole
          imagePullSecrets:
            - name: regcred
