apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: default
  namespace: pihole
imagePullSecrets:
  - name: regcred
