apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "v2.23.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: pihole
      interval: 12h
  values:
    serviceDns:
      type: LoadBalancer
    serviceDhcp:
      type: LoadBalancer
    replicaCount: 1
    serviceWeb:
      annotations:
        traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      http:
        enabled: true
        port: 80
      type: ClusterIP
    resources:
      limits:
        cpu: 400m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    admin:
      existingSecret: "pihole-admin-password"
      passwordKey: "password"
    dnsmasq:
      customDnsEntries:
        - address=/*.horel.io/192.168.0.168
        - address=/horel-k0s-1/192.168.0.204
        - address=/horel-k0s-2/192.168.0.168
        - address=/horel-k0s-3/192.168.0.4
        - address=/horel-k0s-4/192.168.0.177
    adlists:
      #- https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
      #- https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/ultimate.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.plus.txt
      - http://sysctl.org/cameleon/hosts
      - https://o0.pages.dev/Pro/domains.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt
      - https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
      - https://big.oisd.nl
