apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-auth
  namespace: pihole
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-admin-password
  data:
  - secretKey: password
    remoteRef:
      key: kv/pihole/admin
      property: password