#dirty hack that can probably be handled with service account configs
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: pihole
  namespace: pihole
spec:
  selector:
    matchLabels:
      app: pihole
      release: pihole
  template:
    metadata:
      labels:
        app: pihole
        release: pihole
    spec:
      containers:
        - name: pihole
          image: "charleshorel/pihole-secure:latest"
      imagePullSecrets:
        - name: regcred
