apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: horel-ca-issuer
spec:
  vault:
    path: pki_int/sign/horel-dot-io
    server: http://vault.vault.svc.cluster.local:8200
    auth:
      tokenSecretRef:
        name: vault-token
        key: token