server:
  service:
    type: ClusterIP
    servicePortHttp: 8080
  # certificate:
  #   enabled: true
  #   issuer:
  #     kind: "ClusterIssuer"
  #     name: "horel-ca-issuer"
  #   domain: "argocd.horel.io"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 128Mi
configs:
  cm:
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  params:
    server.insecure: true
applicationSet:
  resources:
    limits:
      cpu: '300m'
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
repoServer:
  resources:
    limits:
      cpu: '300m'
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
dex:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
redis:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi
controller:
  resources:
    limits:
      cpu: '500m'
      memory: 800Mi
    requests:
      cpu: 250m
      memory: 150Mi
notifications:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi