server:
  service:
    type: LoadBalancer
    servicePortHttp: 1080
    servicePortHttps: 10443
  certificate:
    enabled: true
    issuer:
      kind: "ClusterIssuer"
      name: "horel-issuer"
    domain: "argocd"
    additionalHosts: 
    - "192.168.0.4"
    - "192.168.0.168"
    - "192.168.0.204"
configs:
  cm:
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'