server:
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
  service:
    type: ClusterIP
    servicePortHttp: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 128Mi
configs:
  cm:
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  params:
    server.insecure: true
applicationSet:
  resources:
    limits:
      cpu: '300m'
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
repoServer:
  resources:
    limits:
      cpu: '300m'
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
dex:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
redis:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
controller:
  resources:
    limits:
      cpu: '500m'
      memory: 800Mi
    requests:
      cpu: 250m
      memory: 150Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
notifications:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack