server:
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
  service:
    type: ClusterIP
    servicePortHttp: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 128Mi
configs:
  cm:
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
    application.instanceLabelKey: argocd.argoproj.io/instance
    url: https://argocd.horel.io
    oidc.config: |
      name: Auth0
      issuer: http://dex.dex.svc.cluster.local
      clientID: <theClientId>
      clientSecret: $argocd-oauth-secret:oidc.auth0.clientSecret
      requestedScopes:
      - openid
      - profile
      - email
  params:
    server.insecure: true
applicationSet:
  resources:
    limits:
      cpu: '300m'
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
repoServer:
  resources:
    limits:
      cpu: '800m'
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations: 
  - effect: "NoSchedule"
    key:  "node-role.kubernetes.io/master" 
    operator: "Exists"
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
dex:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
redis:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
controller:
  resources:
    limits:
      cpu: '500m'
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 150Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack
notifications:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 32Mi
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      selector: 
        release: kube-prometheus-stack