prometheusOperator:
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
grafana:
  admin:
    existingSecret: grafana-admin-creds
    userKey: username
    passwordKey: password
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    enabled: true
    type: LoadBalancer
    port: 3000
prometheus:
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
