prometheusOperator:
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
grafana:
  persistence:
    enabled: true
    storageClassName: local-path
  admin:
    existingSecret: grafana-admin-creds
    userKey: username
    passwordKey: password
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    enabled: true
    type: LoadBalancer
    port: 3000
    portName: aserviceport
prometheus:
  persistentVolume:
    storageClass: "local-path"
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
