prometheusOperator:
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: "ALL"
  persistence:
    type: pvc
    enabled: true
    storageClassName: local-path
    inMemory:
      enabled: false
  admin:
    existingSecret: grafana-admin-creds
    userKey: username
    passwordKey: password
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    enabled: true
    type: ClusterIP
    port: 80
prometheus:
  prometheusSpec:
    scrapeInterval: 10s
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources: 
      limits:
        cpu: 500m
        memory: 1200Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector:    
      horel.io.prometheus: "1"
  tlsProxy:
    enabled: true
  persistentVolume:
    enabled: true
    storageClass: "local-path"
    storageClassName: "local-path"
  
alertmanager:
  alertmanagerSpec:
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 40Mi
