prometheusOperator:
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
grafana:
  persistence:
    type: pvc
    enabled: true
    storageClassName: local-path
    inMemory:
      enabled: false
  admin:
    existingSecret: grafana-admin-creds
    userKey: username
    passwordKey: password
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    enabled: true
    type: ClusterIP
    port: 80
prometheus:
  tlsProxy:
    enabled: true
  persistentVolume:
    storageClass: "local-path"
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
