apiVersion: v1
kind: Service
metadata:
  name: registry-mirror
  namespace: registry-mirror
spec:
  selector:
    horel.io.registry: "1"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer