apiVersion: v1
kind: Service
metadata:
  name: registry-mirror
  namespace: registry-mirror
spec:
  selector:
    horel.io.registry: "1"
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  type: NodePort