apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
  - chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    targetRevision: v2.23.0
    helm:
      releaseName: pihole
      valueFiles:
      - $values/releases/pihole/pihole-values.yaml
  - repoURL: https://github.com/cmhorel/k3s-cluster.git
    ref: values
  destination:
    namespace: pihole
    server: https://kubernetes.default.svc