apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
  project: default
  source:
    repoURL: https://github.com/cmhorel/k3s-cluster.git
    targetRevision: HEAD
    path: taints
  destination:
    server: https://kubernetes.default.svc