apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: horel-ca-issuer
  namespace: vault
spec:
  vault:
    path: pki_int/sign/horel-dot-io
    server: http://vault.vault.svc.cluster.local
    auth:
      tokenSecretRef:
        name: vault-token
        namespace: vault
        key: token