apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: horel-ca-issuer
spec:
  vault:
    path: pki_int/crl
    server: http://vault.vault.svc.cluster.local
    auth:
      tokenSecretRef:
        name: vault-token
        key: token