apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-argo-admin-pw
  namespace: argocd
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs: 
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: argocd-initial-admin-secret 
  data:
    - conversionStrategy: None
      match:
        secretKey:  password
        remoteRef:
          remoteKey: argocd/admin