apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: vault
          key: "token"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-token
#   namespace: vault
# data:
#   token: = 