resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 400Mi
service:
  name: trivy
  #type: LoadBalancer
  port: 4954
  clusterIP: ""
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack