resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 800m
    memory: 400Mi
service:
  name: trivy
  #type: LoadBalancer
  port: 4954
  clusterIP: ""
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
nodeCollector:
  scanJobTolerations:
  - effect: NoSchedule
    key:  node-role.kubernetes.io/master 
    operator: "Exists"
