apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: v0.27.0
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
      interval: 12h
  values:
    #global:
    # serverTelemetry:
    #   prometheusOperator: true
    injector:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    server:
      resources:
        limits:
          cpu: 400m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 156Mi
    # serverTelemetry:

#   serviceMonitor:
#     enabled: true
#     selectors:
#       release: kube-prometheus-stack
#     labels:
#       release: kube-prometheus-stack
