apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: traefik
  namespace: kube-system
spec:
  endpoints:
  - honorLabels: false
    interval: 30s
    port: metrics
    scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
    - "kube-system"
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
