apiVersion: v1
kind: Node
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    horel.io.dronerunner: "true"
  name: horel-k0s-3
