apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: capacitor
      app.kubernetes.io/name: onechart
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: capacitor
        app.kubernetes.io/name: onechart
    spec:
      containers:
        - name: capacitor
          image: ghcr.io/gimlet-io/capacitor:v0.4.2
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 40m
              memory: 70Mi
