global:
  serverTelemetry:
    prometheusOperator: true
injector:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
server:
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
serverTelemetry:
  serviceMonitor:
    enabled: true
    selectors:
      release: kube-prometheus-stack
    labels:
      release: kube-prometheus-stack