VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 20000
    v.cpus = 4
  end
  config.vm.box = "boxen/debian-12"
  config.persistent_storage.enabled = true
  config.persistent_storage.location = "~/code/filebrowser.vdi"
  config.persistent_storage.size = 20000
  config.persistent_storage.mountname = 'filebrowser'
  config.persistent_storage.filesystem = 'ext4'
  config.persistent_storage.mountpoint = '/'
  config.persistent_storage.volgroupname = 'myvolgroup'
  config.vm.network "public_network", bridge: "Wireless LAN adapter Wi-Fi", :mac => "5CA1AB1E0001"
  config.vm.hostname = "horel-k0s-4"
  config.vm.provision :shell, path: "bootstrap.sh", env: {"K3S_TOKEN" => ENV['K3S_TOKEN'], 
                                                          "K3S_URL" => ENV['K3S_URL'], 
                                                          "INSTALL_K3S_EXEC" => ENV['INSTALL_K3S_EXEC']}
end