webhook:
  resources: 
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 100Mi
certController:
  resources: 
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 200Mi
resources: 
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 100Mi

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack