apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave
  namespace: weave
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: HEAD
      sourceRef:
        kind: HelmRepository
        name: weave
        namespace: weave
      interval: 12h
  values:
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: horel-ca-issuer
        cert-manager.io/common-name: weave.horel.io
        traefik.ingress.kubernetes.io/router.middlewares: weave-http-to-https@kubernetescrd
      hosts:
        - host: weave.horel.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: weave-server-tls
          hosts:
            - files.horel.io
    adminUser:
      create: true
      username: admin
