apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oauth
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-oauth-secret
  data:
  - secretKey: oidc.auth0.clientSecret
    remoteRef:
      key: kv/dex/clients/argocd
      property: clientSecret
  