serviceDns:
  type: LoadBalancer
serviceDhcp:
  type: LoadBalancer
replicaCount: 1
serviceWeb:
  http:
    enabled: true
    port: 80
  type: ClusterIP
resources: 
  limits:
    cpu: 400m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
admin:
  existingSecret: "pihole-admin-password"
  passwordKey: "password"
dnsmasq:
  customDnsEntries:
    - address=/*.horel.io/192.168.0.168
    - address=/horel-k0s-1/192.168.0.204
    - address=/horel-k0s-2/192.168.0.168
    - address=/horel-k0s-3/192.168.0.4
    - address=/horel-k0s-4/192.168.0.177

