serviceDns:
  type: LoadBalancer
serviceDhcp:
  type: LoadBalancer
replicaCount: 2
serviceWeb:
  http:
    enabled: true
    port: 11080
  https:
    enabled: true
    port: 11443
  type: LoadBalancer
resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
admin:
  existingSecret: "pihole-admin-password"
  passwordKey: "password"

