apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
   project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: v2.10.8
    helm:
      releaseName: argocd
      valueFiles:
      - $values/releases/argocd/argocd-values.yaml
  - repoURL: https://github.com/cmhorel/k3s-cluster.git
    ref: values