apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
  - chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.5
    helm:
      releaseName: cert-manager
      # valueFiles:
      # - $values/releases/cert-/argocd-values.yaml
  - repoURL: https://github.com/cmhorel/k3s-cluster.git
    ref: values
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc