apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
  - chart: external-secrets
    repoURL: hhttps://charts.external-secrets.io
    targetRevision: v0.9.16
    helm:
      releaseName: external-secrets
      valueFiles:
      - $values/releases/external-secrets/external-secrets-values.yaml
  - repoURL: https://github.com/cmhorel/k3s-cluster.git
    ref: values
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  