apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
  - chart: filebrowser
    repoURL: https://utkuozdemir.org/helm-charts
    targetRevision: 1.0.0
    helm:
      releaseName: filebrowser 
      valueFiles:
      - $values/releases/filebrowser/filebrowser-values.yaml
  - repoURL: https://github.com/cmhorel/k3s-cluster.git
    ref: values
  destination:
    namespace: filebrowser
    server: https://kubernetes.default.svc
  