apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cmhorel/k3s-cluster.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc