apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    directory:
        recurse: true
    repoURL: https://github.com/cmhorel/k3s-cluster.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc