apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  sources:
  - chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: v0.27.0
    helm:
      releaseName: vault
      valueFiles:
      - $values/releases/vault/vault-values.yaml
  - repoURL: https://github.com/cmhorel/k3s-cluster.git
    ref: values
  destination:
    namespace: vault
    server: https://kubernetes.default.svc