ui:
  ingress:
    enabled: true
    className: "traefik"
    annotations: 
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: horel-ca-issuer
      cert-manager.io/common-name: sftpgo.horel.io
      traefik.ingress.kubernetes.io/router.middlewares: sftpgo-http-to-https@kubernetescrd

    hosts:
      - host: sftpgo.horel.io
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: sftpgo-server-tls
      hosts:
        - sftpgo.horel.io
