apiVersion: v1
kind: Pod
metadata:
  name: registry-mirror
  namespace: registry-mirror
  labels:
    horel.io.registry: "1"
spec:
  containers:
  - name: registry
    image: registry:latest
    ports:
    - containerPort: 5000
    volumeMounts:
    - mountPath: "/var/lib/registry"
      name: registry-mirror
  nodeSelector:
    horel.io.registry: "1"
  volumes:
  - name: registry-mirror
    persistentVolumeClaim:  
      claimName: registry-mirror
  tolerations:
  - effect: NoSchedule
    key: k3s-registry
    value: "true"
    operator: "Equal"
  - effect: NoExecute	
    key: node.kubernetes.io/not-ready	
    operator: Exists	
    tolerationSeconds: 300	
  - effect: NoExecute	
    key: node.kubernetes.io/unreachable	
    operator: Exists	
    tolerationSeconds: 300